---
- hosts: "{{ deployIp }}"
  remote_user: root
  tasks:
    - file: "path=/var/app/{{ artifactId }} state=directory"
      delegate_to: localhost
      #从nexus中获取jar包
    - name: get jar from nexus
      maven_artifact:
        group_id: "{{ groupId }}"
        artifact_id: "{{ artifactId }}"
        repository_url: '{{ repository }}'
        dest: "/var/app/{{ artifactId }}/"
        username: "{{ username }}"
        password: "{{ password }}"
        version: "{{ appVersion }}"
      delegate_to: localhost
    - name: copy to dest
      copy:
        src: "/var/app/{{ artifactId }}/"
        dest: "/var/app/"
    - name: delete local package
      file: "path=/var/app/{{ artifactId }} state=absent force=yes"
      delegate_to: localhost
      # 获取上次jar包运行的app
    - name: get pid of api
      tags:
        - getPid
      shell: "ps -ef | grep -v grep | grep  {{ artifactId }} | awk '{print $2}'"
      register: running_processes

    # 发送停止运行信号
    - name: Kill running processes
      shell: "kill {{ item }}"
      tags:
        - killService
      with_items: "{{ running_processes.stdout_lines }}"

    # 等待60s钟，确认获取的到的pid是否都停止运行
    - wait_for:
        path: "/proc/{{ item }}/status"
        state: absent
        timeout: 60
      tags:
        - waitKillService
      with_items: "{{ running_processes.stdout_lines }}"
      ignore_errors: yes
      register: killed_processes
    # 强制杀死，未停止运行的进程
    - name: Force kill stuck processes
      shell: "kill -9 {{ item }}"
      with_items: "{{ killed_processes.results | select('failed') | map(attribute='item') | list }}"

    # 启动新的jar包
    - name: start wechat-api
      shell: "nohup java -jar /var/app/{{ artifactId }}-{{ appVersion }}.jar --name={{ artifactId }}  &"



